name: Requirements File Generator
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Requirements Generation
        id: requirements
      with:
        PROJECT_NAME: DiceGame
        PROJECT_PATH: /
        REQUIREMENT_PATH: /requirement.txt
        
